
[credentials]
[credentials.usernames]
[credentials.usernames.user1]
user = "Abdullah"
password = "$2b$12$NP.JqFgko7sod6qHkZxp/eSSpNjZa.X1e6uVb4kvgqJEJLdN8ODeq"

[credentials.usernames.user2]
user = "Abdelwahab"
password = "12345"

[credentials.usernames.user3]
user = "Hager"
password = "12345"

[credentials.usernames.user4]
user = "Hekmat"
password = "12345"

[credentials.usernames.user5]
user = "Amr"
password = "12345"

[cookie]
name = "TestCookie"
key = "1234567890"
expiry_days = 0

[preauthorized]
  emails = "melsby@gmail.com"